version: '3.8'

services:
  mysql1:
    container_name: mysql1
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: zabbixpass
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix_net

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-latest
    depends_on:
      - mysql1
    environment:
      DB_SERVER_HOST: mysql1
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    ports:
      - "10051:10051"
    restart: unless-stopped
    command: >
      sh -c "sleep 30 && docker-entrypoint.sh"
    networks:
      - zabbix_net

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    environment:
      DB_SERVER_HOST: mysql1
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Stockholm
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - zabbix_net

volumes:
  mysql_data:

networks:
  zabbix_net:
