services:
  mysql:
    container_name: zabbix-mysql
    image: mysql:8.0.34
    command: --max_allowed_packet=256M --wait_timeout=28800
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      MYSQL_ROOT_PASSWORD: zabbixpass
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      ZBX_DEBUGLEVEL: 3
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep zabbix_server"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Den här kollar att Zabbix-server-processen körs

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Stockholm
    ports:
      - "8000:8080"
    restart: unless-stopped
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Den här kollar att webbgränssnittet svarar korrekt

    zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=lia-server
    ports:
      - "10050:10050"
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/10050"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  mysql_data:

networks:
  05_zabbix-docker_zabbix-net:
    external: true
